# fly.toml app configuration file generated for bueno-devs-todo-api on 2024-07-26T18:25:57-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bueno-devs-todo-api'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[deploy]
  release_command = 'npx prisma migrate deploy'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
